### ISSUE TITLE
Switch to hugo

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg.github.io#17]
With [Wercker integration](https://gohugo.io/tutorials/automated-deployments/) running we would only commit markdown files to update the website.

There is a [theme available](http://themes.gohugo.io/material-docs/) which might fit good to MobileOrg

**Comment by mgmart** [comment]
As it seems no discussion is needed for this. :feelsgood: 

Due to #18 I created a [hugo based branch](/MobileOrg/mobileorg.github.io/tree/hugo).
Unfortunately I have not enough privileges on the repo to activate the wercker application.

**Comment by webframp** [comment]
Seems fine to me, what's needed to activate?

**Comment by mgmart** [comment]
Wercker is complaining about my privileges on the repo. Maybe it is sufficient if you grant the same privileges to me as I have for mobileorg.

**Comment by webframp** [comment]
You do have the same permissions on both. It might need more, just a sec

**Comment by mgmart** [comment]
Website is on Hugo now. The CNAME warning is a nice notification that the website has changed :feelsgood:

**Comment by mgmart** [comment]
CNAME warning is gone
