### ISSUE TITLE
Create Credits Page

### ISSUE THREAD

**Issue by mgmart** [MobileOrg/mobileorg.github.io#6]
As the [list in the app setting is growing](https://github.com/MobileOrg/mobileorg/pull/118#pullrequestreview-15603832) it might make sense to store the credits on the website.

In the projects history there are @0-wiz-0 & @russelmcc who have contributed to the project but are not mentioned in the credits. Maybe there are more.

In addition there are the new contributors.

**Comment by webframp** [comment]
This one seems done now?
