### ISSUE TITLE
Site documentation outline

### ISSUE THREAD

**Issue by webframp** [MobileOrg/mobileorg.github.io#7]
We need a rough outline of contents for the documentation sections that should be on the site. We can then start to flesh out the contents.

**Comment by mgmart** [comment]
There exists a draft in Paper which awaits completion 🦄

**Comment by webframp** [comment]
[found it](https://paper.dropbox.com/doc/Outline-for-Website-4H5576d4WK9sikUeBEPNS) thanks

**Comment by mgmart** [comment]
Done for now, I think 🦄
